name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    - name: Getcode
      uses: actions/checkout@v3
    - name: install
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: instal dependecy
      run: | 
          npm ci
          ls -la
    - name: run test
      run:  npm run test 